-- Deletes all data from database.

DELETE FROM mark;
DELETE FROM subject;
DELETE FROM student;
DELETE FROM specialty;
DELETE FROM report_type;
DELETE FROM student_group;
DELETE FROM study_form;

TRUNCATE TABLE subject RESTART IDENTITY CASCADE;
TRUNCATE TABLE student RESTART IDENTITY CASCADE;
TRUNCATE TABLE specialty RESTART IDENTITY CASCADE;
TRUNCATE TABLE report_type RESTART IDENTITY CASCADE;
TRUNCATE TABLE student_group RESTART IDENTITY CASCADE;
TRUNCATE TABLE study_form RESTART IDENTITY CASCADE;
TRUNCATE TABLE mark RESTART IDENTITY CASCADE;
