# Generated by Django 5.1.4 on 2024-12-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'managed': False, 'ordering': ['-mark_id'], 'verbose_name': 'оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='reporttype',
            options={'managed': False, 'ordering': ['report_type_id'], 'verbose_name': 'форма отчетности', 'verbose_name_plural': 'Формы отчетности'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'managed': False, 'ordering': ['specialty_code'], 'verbose_name': 'специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'ordering': ['group', 'last_name', 'first_name', 'family_name'], 'verbose_name': 'студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'managed': False, 'ordering': ['group_id'], 'verbose_name': 'группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='studyform',
            options={'managed': False, 'ordering': ['form_id'], 'verbose_name': 'форма обучения', 'verbose_name_plural': 'Формы обучения'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': False, 'ordering': ['subject_id'], 'verbose_name': 'дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
    ]
